### ISSUE TITLE
Arch script fails if yay isn't installed, even if the AUR dependency is.

### ISSUE THREAD

**Issue by flip-rossi** [Diogo-Paulico/FCT-VPN#12]
I think it should be possible for users to be able to install the AUR dependency (lib32-libstdc++5) manually or through another AUR helper. So the script should check if it is not installed, and, only then try to install with yay.
The README should also indicate that the user should either have the AUR package installed, or yay for automatic installation, since currently there is no indication of what went wrong in the "Dependency set install'" step.

**Comment by ttmx** [comment]
Boas Flip :P
I'll accept the pull request, but be warned, our method seems to be a bit unstable.
Its recommended to use this repository instead, its properly tested and works everywhere with nearly 0 configuration.
https://github.com/ruyrybeyro/chrootvpn
